### ISSUE TITLE
rnn_spn.py gives error

### ISSUE THREAD

**Issue by mongoose54** [skaae/recurrent-spatial-transformer-code#1]
@skaae Congratulations for the publication and releasing the code. I am trying to run `rnn_spn.py` and I am getting the following error:

```
################################################################################
#decayfac                           1.5
#decayinterval                      10
#downsample                         3.0
#dropout                            0.0
#lr                                 0.0005
#nodecay                            30
#optimizer                          rmsprop
################################################################################
<class 'lasagne.layers.conv.Conv2DLayer'>
Filename: mnist_sequence3_sample_8distortions_9x9.npz
(None, 32, 31, 31)
(None, 32, 13, 13)
(None, 32, 15, 15)
(None, 32, 6, 6)
(None, 32, 4, 4)
l_conv0_loc.W
l_conv0_loc.b
l_conv1_loc.W
l_conv1_loc.b
l_conv2_loc.W
l_conv2_loc.b
W_in_to_updategate
W_hid_to_updategate
b_updategate
W_in_to_resetgate
W_hid_to_resetgate
b_resetgate
W_in_to_hidden_update
W_hid_to_hidden_update
b_hidden_update
hid_init
A_net.W
A_net.b
l_conv0_out.W
l_conv0_out.b
l_conv1_out.W
l_conv1_out.b
l_conv2_out.W
l_conv2_out.b
class1.W
class1.b
class2.W
class2.b
Traceback (most recent call last):
  File "rnn_spn.py", line 223, in <module>
    updates=updates)
  File "/Users/alexk/anaconda/lib/python2.7/site-packages/theano/compile/function.py", line 316, in function
    output_keys=output_keys)
  File "/Users/alexk/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.py", line 499, in pfunc
    no_default_updates=no_default_updates)
  File "/Users/alexk/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.py", line 215, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, vector)>, shared_var.type=TensorType(float32, vector), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, vector)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
```

**Comment by skaae** [comment]
My best guess is thay you need to set the float32 in your theanorc file? 

Alternatively you can add

`theano.config.floatX='float32'`

after you have imported theano.

**Comment by mongoose54** [comment]
@skaae It worked. Thanks!

**Comment by skaae** [comment]
@mongoose54 : Did it solve your problem?

EDIT: Somehow missed your previous comment :)
